server:
  port: 8091

spring:
  datasource:
    url: jdbc:h2:mem:testttdb;Mode=Oracle
    username: sa
    password: password
    driver-class-name: org.h2.Driver
  sql:
    init:
      platform: h2
  jpa:
    hibernate:
      ddl-auto: none
    generate-ddl: true
